# .air.toml
[build]
  cmd = "go build -o ./tmp/app ."
  bin = "./tmp/app"
  include_ext = ["go", "tpl", "tmpl", "html", "css", "js"]
  exclude_dir = ["assets", "public", "tmp"]
  delay = 1000

[color]
  main = "yellow"

[log]
  time = true

